//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiVoiceCallRecorderExample.Session {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DnisDidNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MiVoiceCallRecorderExample.Session.ArrayOfString ExtensionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((this.UserGuidField.Equals(value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DnisDidNumber {
            get {
                return this.DnisDidNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DnisDidNumberField, value) != true)) {
                    this.DnisDidNumberField = value;
                    this.RaisePropertyChanged("DnisDidNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIDField, value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public MiVoiceCallRecorderExample.Session.ArrayOfString Extensions {
            get {
                return this.ExtensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionsField, value) != true)) {
                    this.ExtensionsField = value;
                    this.RaisePropertyChanged("Extensions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Session.SessionSoap")]
    public interface SessionSoap {
        
        // CODEGEN: Generating message contract since element name loginClass from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        MiVoiceCallRecorderExample.Session.LoginResponse Login(MiVoiceCallRecorderExample.Session.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.LoginResponse> LoginAsync(MiVoiceCallRecorderExample.Session.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        MiVoiceCallRecorderExample.Session.LogoutResponse Logout(MiVoiceCallRecorderExample.Session.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.LogoutResponse> LogoutAsync(MiVoiceCallRecorderExample.Session.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeepAlive", ReplyAction="*")]
        MiVoiceCallRecorderExample.Session.KeepAliveResponse KeepAlive(MiVoiceCallRecorderExample.Session.KeepAliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeepAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.KeepAliveResponse> KeepAliveAsync(MiVoiceCallRecorderExample.Session.KeepAliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NoOp", ReplyAction="*")]
        void NoOp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NoOp", ReplyAction="*")]
        System.Threading.Tasks.Task NoOpAsync();
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserProfile", ReplyAction="*")]
        MiVoiceCallRecorderExample.Session.GetUserProfileResponse GetUserProfile(MiVoiceCallRecorderExample.Session.GetUserProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.GetUserProfileResponse> GetUserProfileAsync(MiVoiceCallRecorderExample.Session.GetUserProfileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.Session.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(MiVoiceCallRecorderExample.Session.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string loginClass, string username, string password) {
            this.loginClass = loginClass;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.Session.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(MiVoiceCallRecorderExample.Session.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.Session.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(MiVoiceCallRecorderExample.Session.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.Session.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(MiVoiceCallRecorderExample.Session.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogoutResponseBody {
        
        public LogoutResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeepAliveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeepAlive", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.Session.KeepAliveRequestBody Body;
        
        public KeepAliveRequest() {
        }
        
        public KeepAliveRequest(MiVoiceCallRecorderExample.Session.KeepAliveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeepAliveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        public KeepAliveRequestBody() {
        }
        
        public KeepAliveRequestBody(string sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeepAliveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeepAliveResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.Session.KeepAliveResponseBody Body;
        
        public KeepAliveResponse() {
        }
        
        public KeepAliveResponse(MiVoiceCallRecorderExample.Session.KeepAliveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class KeepAliveResponseBody {
        
        public KeepAliveResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserProfile", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.Session.GetUserProfileRequestBody Body;
        
        public GetUserProfileRequest() {
        }
        
        public GetUserProfileRequest(MiVoiceCallRecorderExample.Session.GetUserProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        public GetUserProfileRequestBody() {
        }
        
        public GetUserProfileRequestBody(string sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.Session.GetUserProfileResponseBody Body;
        
        public GetUserProfileResponse() {
        }
        
        public GetUserProfileResponse(MiVoiceCallRecorderExample.Session.GetUserProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MiVoiceCallRecorderExample.Session.UserProfile GetUserProfileResult;
        
        public GetUserProfileResponseBody() {
        }
        
        public GetUserProfileResponseBody(MiVoiceCallRecorderExample.Session.UserProfile GetUserProfileResult) {
            this.GetUserProfileResult = GetUserProfileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionSoapChannel : MiVoiceCallRecorderExample.Session.SessionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionSoapClient : System.ServiceModel.ClientBase<MiVoiceCallRecorderExample.Session.SessionSoap>, MiVoiceCallRecorderExample.Session.SessionSoap {
        
        public SessionSoapClient() {
        }
        
        public SessionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.Session.LoginResponse MiVoiceCallRecorderExample.Session.SessionSoap.Login(MiVoiceCallRecorderExample.Session.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string loginClass, string username, string password) {
            MiVoiceCallRecorderExample.Session.LoginRequest inValue = new MiVoiceCallRecorderExample.Session.LoginRequest();
            inValue.Body = new MiVoiceCallRecorderExample.Session.LoginRequestBody();
            inValue.Body.loginClass = loginClass;
            inValue.Body.username = username;
            inValue.Body.password = password;
            MiVoiceCallRecorderExample.Session.LoginResponse retVal = ((MiVoiceCallRecorderExample.Session.SessionSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.LoginResponse> MiVoiceCallRecorderExample.Session.SessionSoap.LoginAsync(MiVoiceCallRecorderExample.Session.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.LoginResponse> LoginAsync(string loginClass, string username, string password) {
            MiVoiceCallRecorderExample.Session.LoginRequest inValue = new MiVoiceCallRecorderExample.Session.LoginRequest();
            inValue.Body = new MiVoiceCallRecorderExample.Session.LoginRequestBody();
            inValue.Body.loginClass = loginClass;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((MiVoiceCallRecorderExample.Session.SessionSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.Session.LogoutResponse MiVoiceCallRecorderExample.Session.SessionSoap.Logout(MiVoiceCallRecorderExample.Session.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public void Logout(string sessionID) {
            MiVoiceCallRecorderExample.Session.LogoutRequest inValue = new MiVoiceCallRecorderExample.Session.LogoutRequest();
            inValue.Body = new MiVoiceCallRecorderExample.Session.LogoutRequestBody();
            inValue.Body.sessionID = sessionID;
            MiVoiceCallRecorderExample.Session.LogoutResponse retVal = ((MiVoiceCallRecorderExample.Session.SessionSoap)(this)).Logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.LogoutResponse> MiVoiceCallRecorderExample.Session.SessionSoap.LogoutAsync(MiVoiceCallRecorderExample.Session.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.LogoutResponse> LogoutAsync(string sessionID) {
            MiVoiceCallRecorderExample.Session.LogoutRequest inValue = new MiVoiceCallRecorderExample.Session.LogoutRequest();
            inValue.Body = new MiVoiceCallRecorderExample.Session.LogoutRequestBody();
            inValue.Body.sessionID = sessionID;
            return ((MiVoiceCallRecorderExample.Session.SessionSoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.Session.KeepAliveResponse MiVoiceCallRecorderExample.Session.SessionSoap.KeepAlive(MiVoiceCallRecorderExample.Session.KeepAliveRequest request) {
            return base.Channel.KeepAlive(request);
        }
        
        public void KeepAlive(string sessionID) {
            MiVoiceCallRecorderExample.Session.KeepAliveRequest inValue = new MiVoiceCallRecorderExample.Session.KeepAliveRequest();
            inValue.Body = new MiVoiceCallRecorderExample.Session.KeepAliveRequestBody();
            inValue.Body.sessionID = sessionID;
            MiVoiceCallRecorderExample.Session.KeepAliveResponse retVal = ((MiVoiceCallRecorderExample.Session.SessionSoap)(this)).KeepAlive(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.KeepAliveResponse> MiVoiceCallRecorderExample.Session.SessionSoap.KeepAliveAsync(MiVoiceCallRecorderExample.Session.KeepAliveRequest request) {
            return base.Channel.KeepAliveAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.KeepAliveResponse> KeepAliveAsync(string sessionID) {
            MiVoiceCallRecorderExample.Session.KeepAliveRequest inValue = new MiVoiceCallRecorderExample.Session.KeepAliveRequest();
            inValue.Body = new MiVoiceCallRecorderExample.Session.KeepAliveRequestBody();
            inValue.Body.sessionID = sessionID;
            return ((MiVoiceCallRecorderExample.Session.SessionSoap)(this)).KeepAliveAsync(inValue);
        }
        
        public void NoOp() {
            base.Channel.NoOp();
        }
        
        public System.Threading.Tasks.Task NoOpAsync() {
            return base.Channel.NoOpAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.Session.GetUserProfileResponse MiVoiceCallRecorderExample.Session.SessionSoap.GetUserProfile(MiVoiceCallRecorderExample.Session.GetUserProfileRequest request) {
            return base.Channel.GetUserProfile(request);
        }
        
        public MiVoiceCallRecorderExample.Session.UserProfile GetUserProfile(string sessionID) {
            MiVoiceCallRecorderExample.Session.GetUserProfileRequest inValue = new MiVoiceCallRecorderExample.Session.GetUserProfileRequest();
            inValue.Body = new MiVoiceCallRecorderExample.Session.GetUserProfileRequestBody();
            inValue.Body.sessionID = sessionID;
            MiVoiceCallRecorderExample.Session.GetUserProfileResponse retVal = ((MiVoiceCallRecorderExample.Session.SessionSoap)(this)).GetUserProfile(inValue);
            return retVal.Body.GetUserProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.GetUserProfileResponse> MiVoiceCallRecorderExample.Session.SessionSoap.GetUserProfileAsync(MiVoiceCallRecorderExample.Session.GetUserProfileRequest request) {
            return base.Channel.GetUserProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.Session.GetUserProfileResponse> GetUserProfileAsync(string sessionID) {
            MiVoiceCallRecorderExample.Session.GetUserProfileRequest inValue = new MiVoiceCallRecorderExample.Session.GetUserProfileRequest();
            inValue.Body = new MiVoiceCallRecorderExample.Session.GetUserProfileRequestBody();
            inValue.Body.sessionID = sessionID;
            return ((MiVoiceCallRecorderExample.Session.SessionSoap)(this)).GetUserProfileAsync(inValue);
        }
    }
}
