//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiVoiceCallRecorderExample.LiveCalls {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallSearch", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CallSearch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrunkIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TrunkID {
            get {
                return this.TrunkIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TrunkIDField, value) != true)) {
                    this.TrunkIDField = value;
                    this.RaisePropertyChanged("TrunkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIDField, value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LiveCalls.LiveCallsSoap")]
    public interface LiveCallsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TryLookupCall", ReplyAction="*")]
        MiVoiceCallRecorderExample.LiveCalls.TryLookupCallResponse TryLookupCall(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TryLookupCall", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.TryLookupCallResponse> TryLookupCallAsync(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TryLookupCallWithDialable", ReplyAction="*")]
        MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableResponse TryLookupCallWithDialable(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TryLookupCallWithDialable", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableResponse> TryLookupCallWithDialableAsync(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBookMark", ReplyAction="*")]
        MiVoiceCallRecorderExample.LiveCalls.AddBookMarkResponse AddBookMark(MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBookMark", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.AddBookMarkResponse> AddBookMarkAsync(MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecordStart", ReplyAction="*")]
        MiVoiceCallRecorderExample.LiveCalls.RecordStartResponse RecordStart(MiVoiceCallRecorderExample.LiveCalls.RecordStartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecordStart", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.RecordStartResponse> RecordStartAsync(MiVoiceCallRecorderExample.LiveCalls.RecordStartRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecordStop", ReplyAction="*")]
        MiVoiceCallRecorderExample.LiveCalls.RecordStopResponse RecordStop(MiVoiceCallRecorderExample.LiveCalls.RecordStopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecordStop", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.RecordStopResponse> RecordStopAsync(MiVoiceCallRecorderExample.LiveCalls.RecordStopRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCallDataField", ReplyAction="*")]
        MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldResponse GetCallDataField(MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCallDataField", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldResponse> GetCallDataFieldAsync(MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetCallDataField", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MiVoiceCallRecorderExample.LiveCalls.CallSearch))]
        MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldResponse SetCallDataField(MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetCallDataField", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldResponse> SetCallDataFieldAsync(MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExtraCallInfo", ReplyAction="*")]
        MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoResponse GetExtraCallInfo(MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExtraCallInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoResponse> GetExtraCallInfoAsync(MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetExtraCallInfo", ReplyAction="*")]
        MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoResponse SetExtraCallInfo(MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetExtraCallInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoResponse> SetExtraCallInfoAsync(MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TryLookupCallRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TryLookupCall", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequestBody Body;
        
        public TryLookupCallRequest() {
        }
        
        public TryLookupCallRequest(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TryLookupCallRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MiVoiceCallRecorderExample.LiveCalls.CallSearch callSearch;
        
        public TryLookupCallRequestBody() {
        }
        
        public TryLookupCallRequestBody(string sessionID, MiVoiceCallRecorderExample.LiveCalls.CallSearch callSearch) {
            this.sessionID = sessionID;
            this.callSearch = callSearch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TryLookupCallResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TryLookupCallResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.TryLookupCallResponseBody Body;
        
        public TryLookupCallResponse() {
        }
        
        public TryLookupCallResponse(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TryLookupCallResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TryLookupCallResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callID;
        
        public TryLookupCallResponseBody() {
        }
        
        public TryLookupCallResponseBody(bool TryLookupCallResult, string callID) {
            this.TryLookupCallResult = TryLookupCallResult;
            this.callID = callID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TryLookupCallWithDialableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TryLookupCallWithDialable", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequestBody Body;
        
        public TryLookupCallWithDialableRequest() {
        }
        
        public TryLookupCallWithDialableRequest(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TryLookupCallWithDialableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dialable;
        
        public TryLookupCallWithDialableRequestBody() {
        }
        
        public TryLookupCallWithDialableRequestBody(string sessionID, string dialable) {
            this.sessionID = sessionID;
            this.dialable = dialable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TryLookupCallWithDialableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TryLookupCallWithDialableResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableResponseBody Body;
        
        public TryLookupCallWithDialableResponse() {
        }
        
        public TryLookupCallWithDialableResponse(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TryLookupCallWithDialableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TryLookupCallWithDialableResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callID;
        
        public TryLookupCallWithDialableResponseBody() {
        }
        
        public TryLookupCallWithDialableResponseBody(bool TryLookupCallWithDialableResult, string callID) {
            this.TryLookupCallWithDialableResult = TryLookupCallWithDialableResult;
            this.callID = callID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookMarkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBookMark", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequestBody Body;
        
        public AddBookMarkRequest() {
        }
        
        public AddBookMarkRequest(MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBookMarkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string text;
        
        public AddBookMarkRequestBody() {
        }
        
        public AddBookMarkRequestBody(string sessionID, string callID, string subject, string text) {
            this.sessionID = sessionID;
            this.callID = callID;
            this.subject = subject;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookMarkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBookMarkResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.AddBookMarkResponseBody Body;
        
        public AddBookMarkResponse() {
        }
        
        public AddBookMarkResponse(MiVoiceCallRecorderExample.LiveCalls.AddBookMarkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddBookMarkResponseBody {
        
        public AddBookMarkResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordStartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecordStart", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.RecordStartRequestBody Body;
        
        public RecordStartRequest() {
        }
        
        public RecordStartRequest(MiVoiceCallRecorderExample.LiveCalls.RecordStartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecordStartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callID;
        
        public RecordStartRequestBody() {
        }
        
        public RecordStartRequestBody(string sessionID, string callID) {
            this.sessionID = sessionID;
            this.callID = callID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordStartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecordStartResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.RecordStartResponseBody Body;
        
        public RecordStartResponse() {
        }
        
        public RecordStartResponse(MiVoiceCallRecorderExample.LiveCalls.RecordStartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RecordStartResponseBody {
        
        public RecordStartResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordStopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecordStop", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.RecordStopRequestBody Body;
        
        public RecordStopRequest() {
        }
        
        public RecordStopRequest(MiVoiceCallRecorderExample.LiveCalls.RecordStopRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecordStopRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callID;
        
        public RecordStopRequestBody() {
        }
        
        public RecordStopRequestBody(string sessionID, string callID) {
            this.sessionID = sessionID;
            this.callID = callID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordStopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecordStopResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.RecordStopResponseBody Body;
        
        public RecordStopResponse() {
        }
        
        public RecordStopResponse(MiVoiceCallRecorderExample.LiveCalls.RecordStopResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RecordStopResponseBody {
        
        public RecordStopResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallDataFieldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallDataField", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequestBody Body;
        
        public GetCallDataFieldRequest() {
        }
        
        public GetCallDataFieldRequest(MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCallDataFieldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fieldName;
        
        public GetCallDataFieldRequestBody() {
        }
        
        public GetCallDataFieldRequestBody(string sessionID, string callID, string fieldName) {
            this.sessionID = sessionID;
            this.callID = callID;
            this.fieldName = fieldName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallDataFieldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallDataFieldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldResponseBody Body;
        
        public GetCallDataFieldResponse() {
        }
        
        public GetCallDataFieldResponse(MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCallDataFieldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetCallDataFieldResult;
        
        public GetCallDataFieldResponseBody() {
        }
        
        public GetCallDataFieldResponseBody(object GetCallDataFieldResult) {
            this.GetCallDataFieldResult = GetCallDataFieldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCallDataFieldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCallDataField", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequestBody Body;
        
        public SetCallDataFieldRequest() {
        }
        
        public SetCallDataFieldRequest(MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetCallDataFieldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fieldName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public object value;
        
        public SetCallDataFieldRequestBody() {
        }
        
        public SetCallDataFieldRequestBody(string sessionID, string callID, string fieldName, object value) {
            this.sessionID = sessionID;
            this.callID = callID;
            this.fieldName = fieldName;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCallDataFieldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCallDataFieldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldResponseBody Body;
        
        public SetCallDataFieldResponse() {
        }
        
        public SetCallDataFieldResponse(MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetCallDataFieldResponseBody {
        
        public SetCallDataFieldResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExtraCallInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExtraCallInfo", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequestBody Body;
        
        public GetExtraCallInfoRequest() {
        }
        
        public GetExtraCallInfoRequest(MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExtraCallInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key;
        
        public GetExtraCallInfoRequestBody() {
        }
        
        public GetExtraCallInfoRequestBody(string sessionID, string callID, string key) {
            this.sessionID = sessionID;
            this.callID = callID;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExtraCallInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExtraCallInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoResponseBody Body;
        
        public GetExtraCallInfoResponse() {
        }
        
        public GetExtraCallInfoResponse(MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExtraCallInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExtraCallInfoResult;
        
        public GetExtraCallInfoResponseBody() {
        }
        
        public GetExtraCallInfoResponseBody(string GetExtraCallInfoResult) {
            this.GetExtraCallInfoResult = GetExtraCallInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetExtraCallInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetExtraCallInfo", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequestBody Body;
        
        public SetExtraCallInfoRequest() {
        }
        
        public SetExtraCallInfoRequest(MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetExtraCallInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string value;
        
        public SetExtraCallInfoRequestBody() {
        }
        
        public SetExtraCallInfoRequestBody(string sessionID, string callID, string key, string value) {
            this.sessionID = sessionID;
            this.callID = callID;
            this.key = key;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetExtraCallInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetExtraCallInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoResponseBody Body;
        
        public SetExtraCallInfoResponse() {
        }
        
        public SetExtraCallInfoResponse(MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetExtraCallInfoResponseBody {
        
        public SetExtraCallInfoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LiveCallsSoapChannel : MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiveCallsSoapClient : System.ServiceModel.ClientBase<MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap>, MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap {
        
        public LiveCallsSoapClient() {
        }
        
        public LiveCallsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiveCallsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveCallsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveCallsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.LiveCalls.TryLookupCallResponse MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.TryLookupCall(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequest request) {
            return base.Channel.TryLookupCall(request);
        }
        
        public bool TryLookupCall(string sessionID, MiVoiceCallRecorderExample.LiveCalls.CallSearch callSearch, out string callID) {
            MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callSearch = callSearch;
            MiVoiceCallRecorderExample.LiveCalls.TryLookupCallResponse retVal = ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).TryLookupCall(inValue);
            callID = retVal.Body.callID;
            return retVal.Body.TryLookupCallResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.TryLookupCallResponse> MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.TryLookupCallAsync(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequest request) {
            return base.Channel.TryLookupCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.TryLookupCallResponse> TryLookupCallAsync(string sessionID, MiVoiceCallRecorderExample.LiveCalls.CallSearch callSearch) {
            MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.TryLookupCallRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callSearch = callSearch;
            return ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).TryLookupCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableResponse MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.TryLookupCallWithDialable(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequest request) {
            return base.Channel.TryLookupCallWithDialable(request);
        }
        
        public bool TryLookupCallWithDialable(string sessionID, string dialable, out string callID) {
            MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.dialable = dialable;
            MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableResponse retVal = ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).TryLookupCallWithDialable(inValue);
            callID = retVal.Body.callID;
            return retVal.Body.TryLookupCallWithDialableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableResponse> MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.TryLookupCallWithDialableAsync(MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequest request) {
            return base.Channel.TryLookupCallWithDialableAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableResponse> TryLookupCallWithDialableAsync(string sessionID, string dialable) {
            MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.TryLookupCallWithDialableRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.dialable = dialable;
            return ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).TryLookupCallWithDialableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.LiveCalls.AddBookMarkResponse MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.AddBookMark(MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequest request) {
            return base.Channel.AddBookMark(request);
        }
        
        public void AddBookMark(string sessionID, string callID, string subject, string text) {
            MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.subject = subject;
            inValue.Body.text = text;
            MiVoiceCallRecorderExample.LiveCalls.AddBookMarkResponse retVal = ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).AddBookMark(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.AddBookMarkResponse> MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.AddBookMarkAsync(MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequest request) {
            return base.Channel.AddBookMarkAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.AddBookMarkResponse> AddBookMarkAsync(string sessionID, string callID, string subject, string text) {
            MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.AddBookMarkRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.subject = subject;
            inValue.Body.text = text;
            return ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).AddBookMarkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.LiveCalls.RecordStartResponse MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.RecordStart(MiVoiceCallRecorderExample.LiveCalls.RecordStartRequest request) {
            return base.Channel.RecordStart(request);
        }
        
        public void RecordStart(string sessionID, string callID) {
            MiVoiceCallRecorderExample.LiveCalls.RecordStartRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.RecordStartRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.RecordStartRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            MiVoiceCallRecorderExample.LiveCalls.RecordStartResponse retVal = ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).RecordStart(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.RecordStartResponse> MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.RecordStartAsync(MiVoiceCallRecorderExample.LiveCalls.RecordStartRequest request) {
            return base.Channel.RecordStartAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.RecordStartResponse> RecordStartAsync(string sessionID, string callID) {
            MiVoiceCallRecorderExample.LiveCalls.RecordStartRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.RecordStartRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.RecordStartRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            return ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).RecordStartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.LiveCalls.RecordStopResponse MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.RecordStop(MiVoiceCallRecorderExample.LiveCalls.RecordStopRequest request) {
            return base.Channel.RecordStop(request);
        }
        
        public void RecordStop(string sessionID, string callID) {
            MiVoiceCallRecorderExample.LiveCalls.RecordStopRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.RecordStopRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.RecordStopRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            MiVoiceCallRecorderExample.LiveCalls.RecordStopResponse retVal = ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).RecordStop(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.RecordStopResponse> MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.RecordStopAsync(MiVoiceCallRecorderExample.LiveCalls.RecordStopRequest request) {
            return base.Channel.RecordStopAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.RecordStopResponse> RecordStopAsync(string sessionID, string callID) {
            MiVoiceCallRecorderExample.LiveCalls.RecordStopRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.RecordStopRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.RecordStopRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            return ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).RecordStopAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldResponse MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.GetCallDataField(MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequest request) {
            return base.Channel.GetCallDataField(request);
        }
        
        public object GetCallDataField(string sessionID, string callID, string fieldName) {
            MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.fieldName = fieldName;
            MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldResponse retVal = ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).GetCallDataField(inValue);
            return retVal.Body.GetCallDataFieldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldResponse> MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.GetCallDataFieldAsync(MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequest request) {
            return base.Channel.GetCallDataFieldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldResponse> GetCallDataFieldAsync(string sessionID, string callID, string fieldName) {
            MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.GetCallDataFieldRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.fieldName = fieldName;
            return ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).GetCallDataFieldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldResponse MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.SetCallDataField(MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequest request) {
            return base.Channel.SetCallDataField(request);
        }
        
        public void SetCallDataField(string sessionID, string callID, string fieldName, object value) {
            MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.fieldName = fieldName;
            inValue.Body.value = value;
            MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldResponse retVal = ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).SetCallDataField(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldResponse> MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.SetCallDataFieldAsync(MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequest request) {
            return base.Channel.SetCallDataFieldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldResponse> SetCallDataFieldAsync(string sessionID, string callID, string fieldName, object value) {
            MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.SetCallDataFieldRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.fieldName = fieldName;
            inValue.Body.value = value;
            return ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).SetCallDataFieldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoResponse MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.GetExtraCallInfo(MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequest request) {
            return base.Channel.GetExtraCallInfo(request);
        }
        
        public string GetExtraCallInfo(string sessionID, string callID, string key) {
            MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.key = key;
            MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoResponse retVal = ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).GetExtraCallInfo(inValue);
            return retVal.Body.GetExtraCallInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoResponse> MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.GetExtraCallInfoAsync(MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequest request) {
            return base.Channel.GetExtraCallInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoResponse> GetExtraCallInfoAsync(string sessionID, string callID, string key) {
            MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.GetExtraCallInfoRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.key = key;
            return ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).GetExtraCallInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoResponse MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.SetExtraCallInfo(MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequest request) {
            return base.Channel.SetExtraCallInfo(request);
        }
        
        public void SetExtraCallInfo(string sessionID, string callID, string key, string value) {
            MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.key = key;
            inValue.Body.value = value;
            MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoResponse retVal = ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).SetExtraCallInfo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoResponse> MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap.SetExtraCallInfoAsync(MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequest request) {
            return base.Channel.SetExtraCallInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoResponse> SetExtraCallInfoAsync(string sessionID, string callID, string key, string value) {
            MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequest inValue = new MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequest();
            inValue.Body = new MiVoiceCallRecorderExample.LiveCalls.SetExtraCallInfoRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.callID = callID;
            inValue.Body.key = key;
            inValue.Body.value = value;
            return ((MiVoiceCallRecorderExample.LiveCalls.LiveCallsSoap)(this)).SetExtraCallInfoAsync(inValue);
        }
    }
}
